### ISSUE TITLE
Error from show_command_via_API.py

### ISSUE THREAD

**Issue by jonare77** [adolfobolivar/AOS8-InfluDB-Grafana#2]
Can you help me out with this error ?, seems like i get a response from the following line in:
**show_command_via_API.py**,  `AOS_response = AOS_response.json()`

`Traceback (most recent call last):
  File "main.py", line 61, in <module>
    list_associations_per_ap = show_command_via_API.show_command(d[0].get('Switch IP'),token,command)['Association Table']
  File "/home/administrator/AOS8-InfluDB-Grafana/show_command_via_API.py", line 19, in show_command
    AOS_response = AOS_response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by adolfobolivar** [comment]
try downloading the full guide https://community.arubanetworks.com/t5/Wireless-Access/Aruba-AOS8-InfluxDB-and-Grafana-How-to-create-your-own-custom/td-p/480407 " AOS8_Influxdb_Grafana.pdf" .   Test the API call to MM and/or MCs via Postman, then try a small portion of the code, for example, execute just one show command via API

**Comment by BjornarHo** [comment]
Looking good. I only seem to have one small problem...
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    list_ap_statistics_per_radio = show_command_via_API.show_command(d[0].get('Switch IP'),token,command)['RADIO Stats']
KeyError: 'RADIO Stats'


I can't see what's wrong in the script. Could it be that some APs only have 2.4Ghz radio?
